id: PD41B8B94
initial_creation_type: input
source_metadata:
  title: Patrul Rinpoche Series
  language: de
  description: 'Texts by and about the great Rimé master, Dza Patrul Orgyen Jigme
    Chökyi Wangpo (rdza dpal sprul o rgyan ''jigs med chos kyi dbang po, 1808–1887):'
  volume:
    2bd319be93f244bea6fc30d4acd70d66:
      title: Advice for Alak Dongak
      parent: Advice
    5cd272f3e06d4a7eaa8350086fcd1d54:
      title: Advice to Lama Rigdzin Gyatso on Understanding the Influence of Companions
        and Avoiding and Adopting Them Accordingly
      parent: Advice
    8e7c3b1608b94d08830452af95c75fa8:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Advice
    8765059761d04663bb5a10345b2459b4:
      title: The Precious Treasury of Written Instruction Transmitted One-to-One
      parent: Advice
    ab19adacf8934a39b749fc2a4b361866:
      title: Yearning for Mountain Solitude
      parent: Advice
    6adcb6bb190248b09af765e738872850:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    1c66bcee986748c9b1c7b84f4d27f14b:
      title: Biography of Patrul Rinpoche
      parent: Biography
    d4bd242d5abe4ed7ac46bdde40a87174:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
    5c0a1bd0fef94d3db4b3d8256d62c400:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    09df64772f1b4fd9b3f04897260b771f:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Buddhist Philosophy & Teachings
    23c93fab8d4e46bd8052e5385b046a04:
      title: A Brief Introduction to the Bardos
      parent: Buddhist Philosophy & Teachings
    c5e1a1bf8bf14a578ce2bd17ff4279fa:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Buddhist Philosophy & Teachings
    c5c65c6648b74d37b4c5e91d5b2e9619:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Buddhist Philosophy & Teachings
    c5f0ad86f383461fa01d85a5beb62fa0:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Buddhist Philosophy & Teachings
    d8ef5e757bce466dbabdb88aa7a634c9:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Buddhist Philosophy & Teachings
    f9acff0d46014d46bdb1c4f2ea693e86:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Dzogchen
    1d4bf40e2e7a46bebe09c99569360c2f:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Dzogchen
    cfd5ace3bad94258ac88d4f05b46f487:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Ngöndro
    073e2de30eca4188b8451fabf98af930:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Pedagogy
    a54f8fc6e17d4296a504d10d37e931c3:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Pedagogy
    32e13f61b0dd4cbc9ef7e5ca5a70c30f:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    5e2e1746914541918edac6fb637c9651:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    31f7dc5f117a4f268f48f3ba5e0d68da:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
    d8f8f08e7e4245c7b8389b2e035c49ee:
      title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
      parent: Prayers
    7d0b8dd05ac64b04ac715152de240d08:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    ed6e2390ea2a46d8bafbbf589c90d44e:
      title: Prayer to Machik Labdrön
      parent: Prayers
    2e4dc101757d48878d6d9e9f00e573da:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
    cb855b218617409db77cfa66bafd6f1f:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers & Practices
    11e821a7d1bd4c7ca708496d5256dd50:
      title: Temple Dedication Prayer
      parent: Prayers & Practices
    77a4f20394e1454d89deb36ae9ca3814:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    c904bdaef5ac437097cd67443364a726:
      title: The Method for Observing the Eight-Branched One-Day Vow
      parent: Sojong
    bb68d8aa4c954ca5827179300978b433:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    1553ba35b9f94980adb083cc1234c637:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    d6f949fda4454aadb41fc5d3e881bb27:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    c6dd334a68844da8b51f0186ba3f6a90:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Topical Outlines
    6d53517d8b4e4058937a3ae25e820c23:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Topical Outlines
    a39acd4657cd456f89d77a1897e10727:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Topical Outlines
    8df2c759cd80415b9900de67c73fa99f:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    6219467bba664d658964d424f79d8b70:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-03-01T01:13:56.741049'
last_modified_at: '2022-03-01T01:13:56.741052'
